version: 2

jobs:
    build:
        docker:
            -   image: circleci/php:5.6-fpm-browsers
        steps:
            - checkout
            -   run: sudo composer self-update
            -   restore_cache:
                    keys:
                        - composer-v1-{{ checksum "composer.json" }}
                        - composer-v1-
            -   run: composer install --no-interaction --prefer-dist
            -   save_cache:
                    key: composer-v1-{{ checksum "composer.json" }}
                    paths:
                        - vendor
            -   run: ./vendor/bin/phpunit

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
